apiVersion: v1
kind: ConfigMap
metadata:
  name: porter-agent-config
  namespace: porter-agent-system
data:
  PORTER_HOST: "{{ .Values.agent.porterHost }}"
  PORTER_PORT: "{{ .Values.agent.porterPort }}"
  PORTER_TOKEN: "{{ .Values.agent.porterToken }}"
  CLUSTER_ID: "{{ .Values.agent.clusterID }}"
  PROJECT_ID: "{{ .Values.agent.projectID }}"
  LOG_STORE_KIND: "loki"
  LOG_STORE_ADDRESS: "{{ .Values.agent.lokiURL }}"
  SQL_LITE: "true"
  SQL_LITE_PATH: "./agent.db"
