agent:
  image: "public.ecr.aws/o1j4x7p4/porter-agent:latest"
  porterHost: "dashboard.getporter.dev"
  porterPort: "80"
  porterToken: ""
  privateRegistry:
    enabled: false
    secret: ""
  clusterID: ""
  projectID: ""
  lokiURL: porter-agent-loki.porter-agent-system:9095
  lokiHTTPURL: http://porter-agent-loki.porter-agent-system:3100

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}
tolerations: []

loki:
  enabled: true
  isDefault: true
  config:
    limits_config:
      reject_old_samples: true
      # reject samples older than one week
      reject_old_samples_max_age: 168h
      max_concurrent_tail_requests: 50
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
    storage_config:
      boltdb_shipper:
        shared_store: filesystem
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: {}
    uid: ""
  persistence:
    enabled: true
    size: 100Gi
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}-loki.{{ .Release.Namespace }}:3100/loki/api/v1/push
    # See https://github.com/grafana/helm-charts/blob/18282f1780c73130a89ba5e0ee0f8c5721f08b13/charts/promtail/values.yaml#L343
    snippets:
      extraRelabelConfigs:
      - source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_name
          - __meta_kubernetes_pod_annotation_helm_sh_revision
        target_label: porter_pod_name
        action: replace
        separator: '_'
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
