---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBParameterGroup
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    services.k8s.aws/region: {{ .Values.vpcConfig.awsRegion }}
spec:
  name: {{ .Values.config.name }}
  description: "Parameter group for {{ .Values.config.name }}"
  family: postgres{{ (semver (toString .Values.config.engineVersion)).Major }}
  parameterOverrides:
    max_wal_senders: "20"
  tags:
    - key: "porter.run/managed"
      value: "true"
