config:
  allocatedStorage: 30
  awsRegion: ""
  engineMajorVersion: 15
  engineVersion: 15.4
  instanceClass: db.t4g.small
  masterUsername: root
  masterUserPassword: ""
  multiAZ: true
  name: ""
  subnetsIDs: []
