config:
  name: ""
  masterUsername: root
  masterUserPassword: ""
  instanceClass: db.t4g.small
  allocatedStorage: 30
  awsRegion: ""
  engineMajorVersion: 15
  engineVersion: 15.4
  subnetsIDs: []
