config:
  allocatedStorage: 30
  engineVersion: 15.4
  instanceClass: db.t4g.small
  masterUsername: root
  masterUserPassword: ""
  multiAZ: true
  name: ""

vpcConfig:
  awsRegion: ""
  subnetIDs: []
  vpcID: ""
  cidrBlock: ""
  subnetConfig: []
    # - availabilityZone: ""
    #   cidrBlock: ""
