apiVersion: v1
appVersion: 1.15.0
description: A library for hosting, running and scaling dedicated game servers on Kubernetes.
home: https://agones.dev
icon: https://avatars.githubusercontent.com/u/36940055?v=4
keywords:
  - go
  - dedicated-gameservers
  - multiplayer
  - game-development
maintainers:
  - email: agones-discuss@googlegroups.com
    name: agones
    url: https://groups.google.com/forum/#!forum/agones-discuss
name: agones
sources:
  - https://github.com/googleforgames/agones
version: 0.9.0
