{{- if .Values.keda.datadog.enabled -}}
{{- $fullName := include "docker-template.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-datadog-secrets
type: Opaque
data:
  apiKey: {{ .Values.keda.datadog.apiKey | b64enc | quote }}
  appKey: {{ .Values.keda.datadog.appKey | b64enc | quote }}
  datadogSite: {{ .Values.keda.datadog.datadogSite | b64enc | quote }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ $fullName }}-trigger-auth-datadog
spec:
  secretTargetRef:
    # Required: API key for your Datadog account
  - parameter: apiKey
    name: {{ $fullName }}-datadog-secrets
    key: apiKey
    # Required: APP key for your Datadog account
  - parameter: appKey
    name: {{ $fullName }}-datadog-secrets
    key: appKey
    # Optional: Datadog site. Default: "datadoghq.com"
  - parameter: datadogSite
    name: {{ $fullName }}-datadog-secrets
    key: datadogSite
{{- end }}