---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    services.k8s.aws/region: {{ .Values.vpcConfig.awsRegion }}
spec:
  name: {{ .Values.config.name }}
  description: "{{ .Values.config.name }} Subnet Group"
{{- if .Values.vpcConfig.subnetsIDs }}
  subnetIDs:
  {{- range .Values.vpcConfig.subnetsIDs }}
    - {{ toYaml . }}
  {{- end}}
{{- end }}
  tags:
    - key: "porter.run/managed"
      value: "true"
