{{- if ne .Values.image.repository "public.ecr.aws/o1j4x7p4/hello-porter-job" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "docker-template.fullname" . }}
automountServiceAccountToken: true
{{- end }}
