---
name: 'Sync remote directory'
description: 'Sync remote directory to a local directory'

inputs:
  remote_repository:
    description: Remote repository in the form owner/repo e.g. porter-dev/porter
    required: true
  github_token:
    description: 'Github token to use to pull and push the remote'
    required: true

runs:
  using: composite
  steps:
    - name: Set Github Token Env var
      shell: bash
      run: echo "GITHUB_TOKEN=$ {{ inputs.github_token }}"  >> $GITHUB_ENV
    - name: Checkout porter-charts
      shell: bash
      run: gh repo clone ${{ inputs.remote_repository }}
    - name: Copy require directory
      shell: bash
      run: rsync --help


