---
name: 'Sync remote directory'
description: 'Sync remote directory to a local directory'

inputs:
  remote_repository:
    description: Remote repository in the form owner/repo e.g. porter-dev/porter
    required: true
  remote_directory:
    description: Remote directory within the remote_repository to sync
    required: true
  target_directory:
    description: Directory within the current repo, where we would like to copy the files
    required: true
  github_token:
    description: 'Github token to use to pull and push the remote'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout porter-charts
      shell: bash
      env: 
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: gh repo clone ${{ inputs.remote_repository }}
    - name: Copy require directory
      shell: bash
      run: rsync -av 


