apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: porter-ecr-secrets-updater-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: porter-ecr-secrets-updater-svc-acc
    namespace: default
roleRef:
  kind: ClusterRole
  name: porter-ecr-secrets-updater-clusterrole
  apiGroup: rbac.authorization.k8s.io
