apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porter-ecr-secrets-updater-clusterrole
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update"]
