annotations:
  category: Database
apiVersion: v2
appVersion: 6.0.9
description: Open source, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets.
home: https://github.com/bitnami/charts/tree/master/bitnami/redis
icon: https://cdn4.iconfinder.com/data/icons/redis-2/1451/Untitled-2-512.png
keywords:
  - redis
  - cache
  - keyvalue
  - database
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
  - email: cedric@desaintmartin.fr
    name: desaintmartin
name: redis
sources:
  - https://github.com/bitnami/bitnami-docker-redis
  - http://redis.io/
version: 0.12.0
