name: "Sync remote charts in PR"
on:
  push:
    branches: ["sms/cloudwatch-sync"]

jobs:
  sync-chart:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout porter-charts
        uses: actions/checkout@v4
      - name: Update remote chart
        uses: ./.github/actions/sync-remote-directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          remote_repository: aws/eks-charts
