name: "Sync remote charts in PR"
on:
  push:
    branches: ["sms/cloudwatch-sync"]
  # schedule:
  #   - cron: "11 5 * * *"
  # workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.github_token }}
          TEAM_REVIEWERS: engineering
          CONFIG_PATH: .github/charts-to-sync.yml
